# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print("NumPy version: ",np.__version__)
print("\nNumPy Configuration: ", np.show_config)

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
arr = np.zeros(10)
print(arr)

#### 4. How to find the memory size of any array (★☆☆)


Memory Size:

'int8': 1 byte per element.

'int32': 4 bytes per element.


In [ ]:
arr = np.array([2,3], dtype='int8')
print(arr.nbytes)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
vec = np.info(np.array([1, 2], dtype=object))
print(vec)

class:  ndarray
shape:  (2,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x245c0c1ad50
byteorder:  little
byteswap:  False
type: object
None


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
vec = np.zeros(10)
for i in range(5):
    vec[i] = 1
print(vec)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
vec = np.array(range(10,49))
print(vec)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
vec = np.flip(arr)
print(vec)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
matrix = np.arange(9).reshape(3,3)
print(matrix)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [7]:
array = [2,2,0,0,4,0]
for i in range(len(array)):
    if array[i] != 0:
        print(f"{array[i]} is at index {i}")
    else:
        continue

arr = np.nonzero(array)
print(arr)

2 is at index 0
2 is at index 1
4 is at index 4
(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [8]:
id_matrix = np.eye(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
arr  = np.random.random((3, 3, 3))
print(arr)

[[[0.45396701 0.28662512 0.81761921]
  [0.66362734 0.1431847  0.69181243]
  [0.42947461 0.46823828 0.54925183]]

 [[0.6519716  0.3396907  0.81574532]
  [0.61338624 0.34083726 0.41061933]
  [0.81502443 0.33280977 0.26666983]]

 [[0.97875701 0.41280914 0.07739564]
  [0.76717555 0.88138872 0.36632136]
  [0.43104716 0.49818857 0.33250806]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
arr = np.random.random((10,10))
mx = np.max(arr)
mn = np.min(arr)
print(arr)
print("The maximum value of the array:",mx)
print("The minimum value of the array:",mn)

[[0.24677506 0.16596316 0.29624503 0.37261168 0.32238452 0.0270922
  0.86634492 0.75333068 0.24407682 0.43037566]
 [0.46649534 0.03937111 0.08879389 0.63884231 0.06548097 0.81889921
  0.08022714 0.05044673 0.03936123 0.86020288]
 [0.18085307 0.61279939 0.00332732 0.71886595 0.5340095  0.49753717
  0.37709087 0.29074964 0.99943179 0.38663308]
 [0.90443914 0.63749133 0.09705804 0.77476652 0.56486942 0.95483922
  0.55383518 0.17894442 0.50534824 0.76451531]
 [0.70724685 0.11585544 0.79768563 0.31141419 0.27497552 0.23781797
  0.42639277 0.78092152 0.84249027 0.78914946]
 [0.55316808 0.71583035 0.36181078 0.02405289 0.27203984 0.78541214
  0.47575763 0.82972884 0.52294437 0.15941117]
 [0.99088933 0.10980672 0.46239034 0.75910627 0.68717444 0.81596863
  0.35606638 0.52352941 0.07631135 0.65442394]
 [0.873134   0.5570601  0.75179182 0.3859535  0.51847231 0.96946496
  0.57592158 0.03586449 0.71961507 0.00620058]
 [0.24911204 0.40612324 0.87172244 0.18222874 0.49262744 0.47210649
  0.23621971 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [4]:
vec = np.random.rand(30)
vec1 = np.mean(vec)
print(vec)
print("mean= ", vec1)

[0.97642368 0.56193187 0.20349929 0.91707473 0.0511099  0.5101725
 0.43323847 0.18758651 0.08336959 0.82956624 0.2419584  0.11383227
 0.11500895 0.14918896 0.11714738 0.9282135  0.94235141 0.54478521
 0.82831935 0.52008803 0.7622631  0.27074956 0.04998886 0.25594397
 0.21470529 0.34058613 0.85410939 0.40772458 0.17979196 0.92092574]
mean=  0.4503884947210793


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [8]:
arr = np.ones((5,5), dtype=int)
arr[1:-1,1:-1] = 0
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [11]:
arr = np.ones((3,3))
arr = np.pad(arr,pad_width= 2, mode= 'constant', constant_values=(0))
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
## 0 * np.nan => nan , because any values product with nan = nan
# np.nan == np.nan => False , because nan values are not equal to  each other in Numpy
# np.inf > np.nan => False , compersion involving nan the resulr is usually False
# np.nan - np.nan => nan because any values subtract with nan = nan
# np.nan in set([np.nan]) => True , np.nan is considered as an element of the set
# 0.3 == 3 * 0.1 => True

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [5]:
import numpy as np
arr = np.zeros((5,5), dtype= int)
np.fill_diagonal(arr, [1,2,3,4])
arr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 1]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [3]:
arr = np.zeros((8,8),dtype= int)

arr[1::2,::2] = 1 ## odd rows and even colums
arr[::2,1::2] = 0 ## even rows and odd columns 
print(arr)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [32]:
arr = np.unravel_index(99,(6,7,8))
arr


(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [15]:
arr = np.array([5,1])

vec =np.tile(arr,(8,4))
print("vec:\n",vec)
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print("\n z:\n",Z)

vec:
 [[5 1 5 1 5 1 5 1]
 [5 1 5 1 5 1 5 1]
 [5 1 5 1 5 1 5 1]
 [5 1 5 1 5 1 5 1]
 [5 1 5 1 5 1 5 1]
 [5 1 5 1 5 1 5 1]
 [5 1 5 1 5 1 5 1]
 [5 1 5 1 5 1 5 1]]

 z:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [19]:
arr = np.random.random((5,5))
print("original array:\n",arr)
nArr = (arr-np.mean(arr))/np.std(arr)
print("\nNormalized array:\n", nArr)

original array:
 [[0.46295181 0.43292382 0.22615965 0.78876052 0.87176086]
 [0.99345106 0.42512635 0.01209549 0.35716192 0.24183505]
 [0.13561566 0.58367586 0.74182489 0.20687193 0.12792378]
 [0.16028462 0.36980975 0.3687231  0.77648422 0.67383386]
 [0.15022293 0.90897964 0.0543154  0.89479813 0.72191401]]

Normalized array:
 [[-0.01525479 -0.11596606 -0.80943499  1.07747908  1.35585495]
 [ 1.76399324 -0.1421181  -1.52738743 -0.37006484 -0.75686108]
 [-1.11311159  0.38964308  0.92006108 -0.8741243  -1.13890948]
 [-1.03037408 -0.32764513 -0.33128966  1.03630546  0.69202514]
 [-1.06412011  1.48068348 -1.38578555  1.43311994  0.85328173]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [31]:
color = [[('r' , np.ubyte),
          ('g',np.ubyte),
          ('b',np.ubyte),
          ('a',np.ubyte),]]
color

[[('r', numpy.uint8),
  ('g', numpy.uint8),
  ('b', numpy.uint8),
  ('a', numpy.uint8)]]

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [76]:
arr1 = np.random.random((5,3))
print(arr1)
arr2 = np.random.random((3,2))
print("\n\n",arr2)

prd = np.dot(arr1,arr2)
prd

[[0.93949894 0.89482735 0.59789998]
 [0.92187424 0.0884925  0.19598286]
 [0.04522729 0.32533033 0.38867729]
 [0.27134903 0.82873751 0.35675333]
 [0.28093451 0.54269608 0.14092422]]


 [[0.80219698 0.07455064]
 [0.98688694 0.77224477]
 [0.19871568 0.00552212]]


array([[1.75556874, 0.76436767],
       [0.86580169, 0.13814643],
       [0.43458172, 0.25675269],
       [1.10643808, 0.66218749],
       [0.78894834, 0.44081626]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [23]:
arr = np.arange(11)
arr
arr[(arr>3)& (arr<8)] *=-1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [35]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [13]:
z = np.ones((5,5))
print(z ** z) # legal
#print(2 << z >> 2) # ilegal
print( z <- z) # legal
print(1j*z) #legal
print(z/1/1) #legal
##print(z<z>z) #ilegal So, when you combine these two conditions using the and logical operator, the overall expression z < z > z will be False.

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[[0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j]
 [0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j]
 [0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j]
 [0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j]
 [0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [33]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\miree\AppData\Local\Temp\ipykernel_15144\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\miree\AppData\Local\Temp\ipykernel_15144\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\miree\AppData\Local\Temp\ipykernel_15144\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [37]:
arr = [1,2,7,8]
arr1 = [1,5,7,6]
cm = np.intersect1d(arr,arr1)
cm

array([1, 7])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


C:\Users\miree\AppData\Local\Temp\ipykernel_15144\2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [38]:
from datetime import datetime,timedelta
today = datetime.now().date()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)
print("Yesterday: ",yesterday,"Today: " , today , "Tomorrow: ", tomorrow)

Yesterday:  2024-02-22 Today:  2024-02-23 Tomorrow:  2024-02-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [41]:
arr= np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(arr)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [57]:
a = np.arange(10)
print("-the values of the first array: ",a)
b = np.arange(10)
print("\n-The values of the secod array: \n\n", b)
sum = np.add(a,b)
print("\n -the sum of the two array: \n\n", sum)
div = np.divide(-a,2)
div
prod = (np.multiply(sum,div))
prod

-the values of the first array:  [0 1 2 3 4 5 6 7 8 9]

-The values of the secod array: 

 [0 1 2 3 4 5 6 7 8 9]

 -the sum of the two array: 

 [ 0  2  4  6  8 10 12 14 16 18]


array([  0.,  -1.,  -4.,  -9., -16., -25., -36., -49., -64., -81.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [55]:
arr = np.random.random(10) * 10
print("Orginal array",arr,"\n")
m1 = arr.astype(int)
print("Methos 1: ",m1)
m2 = np.floor(arr)
print("Methos 2: ",m2)
m3 = np.trunc(arr)
print("Methos 3: ",m3)
m4 = list(map(int,arr))
''' 
map(int, arr): The map function takes two arguments - a function (int in this case) and an iterable (arr). 
It applies the specified function (int) to each element of the iterable.
list(...): The list() constructor is used to convert the result of the map function into a list.
'''
print("Methos 4: ",m4)

Orginal array [7.9980883  4.63434011 9.20623401 4.67193081 9.85217542 9.90004481
 7.07579773 1.04247321 4.551514   9.65297245] 

Methos 1:  [7 4 9 4 9 9 7 1 4 9]
Methos 2:  [7. 4. 9. 4. 9. 9. 7. 1. 4. 9.]
Methos 3:  [7. 4. 9. 4. 9. 9. 7. 1. 4. 9.]
Methos 4:  [7, 4, 9, 4, 9, 9, 7, 1, 4, 9]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [68]:
vec = np.zeros((5,5))
vec += np.arange(5)
vec

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [57]:
def generate():
    for i in range(10):
        yield i
arr = np.fromiter(generate(),dtype=float,count=-1) # count = -1  mean read all items
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [20]:
vec = np.linspace(0,1,10)
vec

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [8]:
vec = np.random.rand(10)
vec1 = np.sort(vec)
vec1

array([0.15000109, 0.16824774, 0.25618416, 0.49795697, 0.64940573,
       0.70152784, 0.76072105, 0.77685366, 0.78118441, 0.90393383])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [23]:
arr1 = [1,2,3,4]
vec = np.sum(arr1)
vec

10

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [28]:
np.random.seed(42)
a =np.random.rand(5)
print(a)
b = np.random.rand(5)
print(b)
check = np.equal(a,b)
check

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]


array([False, False, False, False, False])

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [30]:
vec = np.array((5,5), dtype= int)
vec = np.ones(vec)
print(vec)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [77]:
arr = np.random.randint(0,3,(3,10))
arr
arr = np.any(axi )

array([[2, 2, 0, 2, 2, 0, 2, 0, 1, 2],
       [1, 0, 2, 0, 1, 0, 2, 2, 1, 0],
       [2, 1, 2, 2, 0, 2, 0, 2, 1, 2]])

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)